GET http://localhost:5288/brands

###
GET http://localhost:5288/brands/2

###
POST http://localhost:5288/brands
Content-Type: application/json

{
    "Name": "Kain"
}

###
PUT http://localhost:5288/brands/1
Content-Type: application/json

{
    "Name": "Looz"
}

###
DELETE http://localhost:5288/brands/2